name       : babashka
version    : 0.7.5
release    : 1
source     :
    - git|https://github.com/babashka/babashka.git : v0.7.5
license    : EPL-1.0
component  : programming.tools
networking : yes
summary    : Babashka is a native Clojure interpreter for scripting with fast startup.
description: |
    Babashka is a native Clojure interpreter for scripting with fast startup. Its main goal is to leverage Clojure in places where you would be using bash otherwise.
builddeps  :
    - leiningen
    - graalvm
    - openjdk-11
environment: |
    export GRAALVM_HOME=/usr/share/graalvm/
    export JAVA_HOME=/usr/share/graalvm/
    export JAVA_CMD=/usr/lib64/openjdk-11/bin/java
build      : |
    # make lein use a temporary location for deps
    sed -i '5 i :local-repo "/tmp/.m2/repo"' project.clj
    ./script/uberjar
    ./script/compile
install    : |
    install -Dm00755 ./bb $installdir/usr/bin/bb
